# Generated by Django 5.0.6 on 2024-07-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabeldi_app', '0002_contactform_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePage', models.CharField(max_length=20)),
                ('click', models.BooleanField()),
            ],
        ),
    ]
